Calculator/Controllers/CalculatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Calculator.Controllers
{
    public class CalculatorController : Controller
    {
        //
        // GET: /Calculator/

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Compute(int num1, int num2, string op)
        {
            int result = 0;

            switch (op)
            {
                case "+":
                    result = num1 + num2;
                    break;
                case "-":
                    result = num1 - num2;
                    break;
                case "/":
                    result = num1 / num2;
                    break;
                case "*":
                    result = num1 * num2;
                    break;
            }

            return View(result);
        }

        

    }
}

Calculator/Views/Calculator/Compute.cshtml
@model Int32

@{
    ViewBag.Title = "Compute";
}

<h2>Result Page</h2>


<p>Result is: @Model</p>

<br />
<a href="@Url.Action("Index","Calculator")">Back</a>

Calculator/Views/Calculator/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@*<script type="text/javascript">
    $(function () {
        $("#btnCompute").click(function () {
            var firstNum = $("#txtFistNum").val();
            var secNum = $("#txtSecondNum").val();

            var url = "";

            


            $.ajax({
                url: '@Url.Action("")'
            });
        });
    });
</script>
*@



<h2>Basic Calculator</h2>

@using (Html.BeginForm("Compute", "Calculator"))
{
    <label>First Number:</label>
    <input type="text" id="num1" name="num1" />

    <select id="op" name="op">
        <option value="+">+</option>
        <option value="-">-</option>
        <option value="/">/</option>
        <option value="*">*</option>
    </select>

    <label>Second Number:</label>
    <input type="text" id="num2" name="num2" />

    <br />
    <input type="submit" value="Compute" id="btnCompute" />
}